### ISSUE TITLE
One problem

### ISSUE THREAD

**Issue by ChenHongBo0420** [TomerGeva/CommDspy#1]
Greetings, thank you for your selfless sharing.
I feel that the effect of FFE-DFE is worse than FFE, is there a problem somewhere?
Looking forward to your reply

**Comment by TomerGeva** [comment]
Hi Chen,
Applying the DFE with the FFE is a little bit trickier than applying an FFE alone. Therefore, if it is not done correctly you can see worse results when applying the DFE incorrectly. Can you please share with me the implementation you wrote? I will add an implementation for this in the package as well for brevity in the coming week. 
Thank you for your interest and feedback,
Tomer

**Comment by ChenHongBo0420** [comment]
Thank you very much, TomerGeva.
I'm new here an d I'm trying to do an equalizer comparison.
In equalization_estimation.py, I noticed that you have written about using DFE for equalization in line 132.
But when I used it(I put ffe_postcursor=0, ffe_precursor=anyother, dfe_taps=anyother) and got the DFE output
, The BER is worse than FFE and the eye diagram does not display properly.
So that I tried to write one myself, but it doesn't fit perfectly into your code.
def ffe_dfe(rsig, const, ntaps_ffe=5, ntaps_dfe=1, passes=1, mu=1e-3, hffe_init=[], hdfe_init=[], update_equalizer=True):
    # initialize FFE
    if len(hffe_init) == 0:
        htaps_ffe = int((ntaps_ffe - 1) / 2)
        hffe = np.zeros((ntaps_ffe,), dtype=float)
        hffe[htaps_ffe] = 1
    else:
        hffe = hffe_init
        ntaps_ffe = len(hffe_init)
        htaps_ffe = int((ntaps_ffe - 1) / 2)
    sffe = 0.0

    # initialize DFE
    if len(hdfe_init) == 0:
        hdfe = np.zeros((ntaps_dfe,), dtype=float)
    else:
        hdfe = hdfe_init
        ntaps_dfe = len(hdfe)
    sdfe = 0.0

    # prepare output signal
    sout = np.zeros((len(rsig),), dtype=float)
    dout = np.zeros((int(len(rsig) / 2),))
    errout = np.zeros((int(len(rsig) * passes / 2),), dtype=float)
    erroutcount = 0
    # cycles
    for p in range(passes):
        for s in range(ntaps_ffe - 1, len(rsig) - ntaps_ffe):
            # ffe output
            sffe = np.dot(hffe, rsig[(s - htaps_ffe):(s + htaps_ffe + 1)])
            # print( rsig[s], sffe )

            # compute signal output
            sout[s] = sffe - sdfe

            # if we are in a mid sample, there is nothing else to do
            if s % 2 == 1:
                continue

            # symbol decision
            posconst = np.argmin(np.abs(sout[s] - const))
            dpos = int(s / 2)
            dout[dpos] = const[posconst]
            #            print( "symbol: ", dout[ int( s / 2 ) ] )

            # dfe output
            sdfe = np.dot(hdfe, dout[(dpos - ntaps_dfe + 1):(dpos + 1)])

            # update equalizers
            err = sout[s] - dout[dpos]
            errout[erroutcount] = err
            erroutcount += 1
            if update_equalizer:
                hffe -= mu * err * rsig[(s - htaps_ffe):(s + htaps_ffe + 1)]
                hdfe -= mu * err * dout[(dpos - ntaps_dfe + 1):(dpos + 1)]

    return sout, hffe, hdfe, errout
This is slightly different from your implementation and I hope it will inspire you.
Looking forward your reply!

**Comment by TomerGeva** [comment]
Hi Chen,
I want to thank you for your question, it helped discover a hidden bug in the DFE calculations. 
The DFE calculation you performed is called LMS and is an iterative method which works well. Nevertheless, I used LS which can compute the optimal MMSE value without iterations, which seems a better choice for this package. There was a bug in the DFE computation which is fixed, and I also added the 'ffe_dfe' function to pass a signal through the FFE and DFE setup. correctly. Please let me know if you have any other questions regarding this issue. All the updates are in this git and the implementation is available in PyPi for version 0.1.2

Tomer
