### ISSUE TITLE
Sorry to bother you again

### ISSUE THREAD

**Issue by ChenHongBo0420** [TomerGeva/CommDspy#2]
Thank you for your generous reply! But I still have some confusion:
When I set up the prbs_len = 2^n -1, for example(prbs13 = 8191, prbs15= 32767),The result is very good, BER = 0.
1.When I changed full_scale, making the value True, BER attenuated considerably but the Eye Diagram did not change much.
2.When I changed PRBS_len= Other values, BER and Eye Diagram were significantly worse.
I would be grateful if I could get your help!
Looking forward your reply!

**Comment by TomerGeva** [comment]
Hi Chen,
I want to thank you for your question. There was indeed a problem which led to these unusual results. After debugging I found a bug in the de-mapping function and In addition I found that the tx_example from the README is written to handle only complete PRBS multiplications. I will change the bug and the example to fit any length of symbols ASAP and will let you know as soon as the new version is uploaded.

Tomer

**Comment by TomerGeva** [comment]
Hi Chen, I wanted to let you know that this problem is now resolved in the git and is available to be used in the 0.1.2 version of this package in the PyPi. Please let me know if you have any other question regarding this subject.

Tomer
